spring:
    profiles:
        active:
        - dev

---
server:
  port: 8001

mybatis:
#  type-aliases-package: cn.com.zhanss.entity            # 所有Entity别名类所在的包
  config-location: classpath:mybatis/mybatis-config.xml # mybatis配置文件
  mapper-locations:
    - classpath:mybatis/mapper/**/*Mapper.xml           # mapper映射文件

spring:
  profiles: dev  # 开发环境
  application:
    name: microservicecloud-config-dept-client          # 微服务对外暴露的名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource        # 当前数据库操作类型
    driver-class-name: org.gjt.mm.mysql.Driver          # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                       # 数据库连接池最小空闲数
      initial-size: 5                                   # 初始化连接数
      max-total: 5                                      # 最大连接数
      max-wait-millis: 200                              # 等待连接的最大超时时间
eureka:
#  server: enable-self-preservation: false 禁用Eureka 自我保护模式
  client:      # 客户端注册进eureka服务列表内
    service-url:
#      注册到Eureka 集群上
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-config-dept-client8001  # 自定义服务名称
    prefer-ip-address: true    # 访问路径可以显示IP地址

info:  # 配置微服务info请求内容
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server:
    port: 8002
mybatis:
#  type-aliases-package: cn.com.zhanss.entity            # 所有Entity别名类所在的包
  config-location: classpath:mybatis/mybatis-config.xml # mybatis配置文件
  mapper-locations:
    - classpath:mybatis/mapper/**/*Mapper.xml           # mapper映射文件

spring:
  profiles: test  # 开发环境
  application:
    name: microservicecloud-config-dept-client          # 微服务对外暴露的名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource        # 当前数据库操作类型
    driver-class-name: org.gjt.mm.mysql.Driver          # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB02
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                       # 数据库连接池最小空闲数
      initial-size: 5                                   # 初始化连接数
      max-total: 5                                      # 最大连接数
      max-wait-millis: 200                              # 等待连接的最大超时时间
eureka:
#  server: enable-self-preservation: false 禁用Eureka 自我保护模式
  client:      # 客户端注册进eureka服务列表内
    service-url:
#      注册到Eureka 集群上
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-config-dept-client8002  # 自定义服务名称
    prefer-ip-address: true    # 访问路径可以显示IP地址

info:  # 配置微服务info请求内容
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

# 请保存为UTF-8格式
